import React from "react";

const PressTable = ({data}) => {
    return (
        <table className="pressTb">
            <thead>
                <tr>
                    <th>구분</th>
                    <th>구분</th>
                    <th>수압1</th>
                    <th>수압2</th>
                    <th>수압3</th>
                    <th>수압4</th>
                    <th>수압5</th>
                    <th>수압6</th>
                    <th>수압7</th>
                    <th>수압8</th>
                    <th>수압9</th>
                    <th>수압10</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td rowSpan="3">A라인(보령방향)</td>
                    <td>평균</td>
                    <td>{data.A.avg.PRESS1}</td>
                    <td>{data.A.avg.PRESS2}</td>
                    <td>{data.A.avg.PRESS3}</td>
                    <td>{data.A.avg.PRESS4}</td>
                    <td>{data.A.avg.PRESS5}</td>
                    <td>{data.A.avg.PRESS6}</td>
                    <td>{data.A.avg.PRESS7}</td>
                    <td>{data.A.avg.PRESS8}</td>
                    <td>{data.A.avg.PRESS9}</td>
                    <td>{data.A.avg.PRESS10}</td>
                </tr>
                <tr>
                    <td>최대</td>
                    <td>{data.A.max.PRESS1}</td>
                    <td>{data.A.max.PRESS2}</td>
                    <td>{data.A.max.PRESS3}</td>
                    <td>{data.A.max.PRESS4}</td>
                    <td>{data.A.max.PRESS5}</td>
                    <td>{data.A.max.PRESS6}</td>
                    <td>{data.A.max.PRESS7}</td>
                    <td>{data.A.max.PRESS8}</td>
                    <td>{data.A.max.PRESS9}</td>
                    <td>{data.A.max.PRESS10}</td>
                </tr>
                <tr>
                    <td>최소</td>
                    <td>{data.A.min.PRESS1}</td>
                    <td>{data.A.min.PRESS2}</td>
                    <td>{data.A.min.PRESS3}</td>
                    <td>{data.A.min.PRESS4}</td>
                    <td>{data.A.min.PRESS5}</td>
                    <td>{data.A.min.PRESS6}</td>
                    <td>{data.A.min.PRESS7}</td>
                    <td>{data.A.min.PRESS8}</td>
                    <td>{data.A.min.PRESS9}</td>
                    <td>{data.A.min.PRESS10}</td>
                </tr>
                <tr>
                    <td rowSpan="3">B라인(태안방향)</td>
                    <td>평균</td>
                    <td>{data.B.avg.PRESS1}</td>
                    <td>{data.B.avg.PRESS2}</td>
                    <td>{data.B.avg.PRESS3}</td>
                    <td>{data.B.avg.PRESS4}</td>
                    <td>{data.B.avg.PRESS5}</td>
                    <td>{data.B.avg.PRESS6}</td>
                    <td>{data.B.avg.PRESS7}</td>
                    <td>{data.B.avg.PRESS8}</td>
                    <td>{data.B.avg.PRESS9}</td>
                    <td>{data.B.avg.PRESS10}</td>
                </tr>
                <tr>
                    <td>최대</td>
                    <td>{data.B.max.PRESS1}</td>
                    <td>{data.B.max.PRESS2}</td>
                    <td>{data.B.max.PRESS3}</td>
                    <td>{data.B.max.PRESS4}</td>
                    <td>{data.B.max.PRESS5}</td>
                    <td>{data.B.max.PRESS6}</td>
                    <td>{data.B.max.PRESS7}</td>
                    <td>{data.B.max.PRESS8}</td>
                    <td>{data.B.max.PRESS9}</td>
                    <td>{data.B.max.PRESS10}</td>
                </tr>
                <tr>
                    <td>최소</td>
                    <td>{data.B.min.PRESS1}</td>
                    <td>{data.B.min.PRESS2}</td>
                    <td>{data.B.min.PRESS3}</td>
                    <td>{data.B.min.PRESS4}</td>
                    <td>{data.B.min.PRESS5}</td>
                    <td>{data.B.min.PRESS6}</td>
                    <td>{data.B.min.PRESS7}</td>
                    <td>{data.B.min.PRESS8}</td>
                    <td>{data.B.min.PRESS9}</td>
                    <td>{data.B.min.PRESS10}</td>
                </tr>
            </tbody>
        </table>
    )
}

export default PressTable;