export const UPDATE_VALUE = 'UPDATE_VALUE';
export const REMOVE_VALUE = 'REMOVE_VALUE';
export const INIT_DATA = 'INIT_DATA';
export const INIT_FLOW_SET_DATA = 'INIT_FLOW_SET_DATA';
export const INIT_PRESS_SET_DATA = 'INIT_PRESS_SET_DATA';
